[pyprland]
plugins = ["scratchpads", "menubar"]

[menubar]
command = "waybar"
monitors = ["HDMI-1", "eDP-1"]

[scratchpads.term]
animation = "fromTop"
command = "alacritty --class=term.alacritty.scratchpad -e tmux new-session -A -s dropterm"
class = "term.alacritty.scratchpad"
size = "75% 60%"

[scratchpads.music]
animation = "fromTop"
command = "alacritty --class=music.alacritty.scratchpad -e ncmpcpp"
lazy = true
class = "music.alacritty.scratchpad"
size = "75% 60%"
unfocus = "hide"

[scratchpads.top]
animation = "fromTop"
command = "alacritty --class=top.alacritty.scratchpad -e btm"
lazy = true
class = "top.alacritty.scratchpad"
size = "75% 60%"

[scratchpads.fm]
animation = "fromTop"
command = "alacritty --class=fm.alacritty.scratchpad -e lf"
class = "fm.alacritty.scratchpad"
lazy = true
size = "75% 60%"

[scratchpads.volume]
animation = "fromRight"
command = "alacritty --class=volume.alacritty.scratchpad -e pulsemixer"
class = "volume.alacritty.scratchpad"
lazy = true
size = "40% 90%"
unfocus = "hide"
