[pyprland]
plugins = ["scratchpads"]

[scratchpads.term]
animation = "fromTop"
command = "ghostty --class=term.ghostty.scratchpad -e tmux new-session -A -s dropterm"
class = "term.ghostty.scratchpad"
size = "75% 60%"

[scratchpads.music]
animation = "fromTop"
command = "ghostty --class=music.ghostty.scratchpad -e ncmpcpp"
lazy = true
class = "music.ghostty.scratchpad"
size = "75% 60%"
unfocus = "hide"

[scratchpads.top]
animation = "fromTop"
command = "ghostty --class=top.ghostty.scratchpad -e btm"
lazy = true
class = "top.ghostty.scratchpad"
size = "75% 60%"

[scratchpads.fm]
animation = "fromTop"
command = "ghostty --class=fm.ghostty.scratchpad -e lf"
class = "fm.ghostty.scratchpad"
lazy = true
size = "75% 60%"

[scratchpads.volume]
animation = "fromRight"
command = "ghostty --class=volume.ghostty.scratchpad -e pulsemixer"
class = "volume.ghostty.scratchpad"
lazy = true
size = "40% 90%"
unfocus = "hide"
