[pyprland]
plugins = ["scratchpads", "monitors"]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm -- tmux new-session -A -s dropterm"
class = "kitty-dropterm"
size = "75% 60%"

[scratchpads.music]
animation = "fromTop"
command = "kitty --class kitty-dropmusic -- ncmpcpp"
lazy = true
class = "kitty-dropmusic"
size = "75% 60%"
unfocus = "hide"

[scratchpads.top]
animation = "fromTop"
command = "kitty --class kitty-droptop -- btm"
lazy = true
class = "kitty-droptop"
size = "75% 60%"

[scratchpads.fm]
animation = "fromTop"
command = "kitty --class kitty-dropfm -- lf"
class = "kitty-dropfm"
lazy = true
size = "75% 60%"

[scratchpads.volume]
animation = "fromRight"
command = "kitty --class kitty-dropvolume -- pulsemixer"
class = "kitty-dropvolume"
lazy = true
size = "40% 90%"
unfocus = "hide"

[monitors.placement]
"AOC".topCenterOf = "BOE"
