[pyprland]
plugins = [
  "scratchpads",
  "shift_monitors",
  "workspaces_follow_focus"
]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm -- tmux new-session -A -s dropterm"
class = "kitty-dropterm"
size = "75% 60%"

[scratchpads.music]
animation = "fromTop"
command = "kitty --class kitty-dropmusic -- ncmpcpp"
class = "kitty-dropmusic"
size = "75% 60%"

[scratchpads.top]
animation = "fromTop"
command = "kitty --class kitty-dropbtm -- btm"
class = "kitty-dropbtm"
size = "75% 60%"

[scratchpads.fm]
animation = "fromTop"
command = "kitty --class kitty-droplf -- lf"
class = "kitty-droplf"
size = "75% 60%"

[scratchpads.volume]
animation = "fromRight"
command = "pavucontrol"
class = "pavucontrol"
lazy = true
size = "40% 90%"
unfocus = "hide"

[monitors.placement]
"AOC".topOf = "BOE"
