################################
##
##   Default config for Aria2TUI
##
##   Some common options have been commented.
##
################################



[general]

port = 6800
token = "`:rL'6gbCaRT{n6frTbAX6$fb[h~3F7X"
url = "http://localhost"

# Used for starting and restarting.
startupcmds = ["systemctl --user start aria2cd"]
restartcmds = ["systemctl --user restart aria2cd", "notify-send 'Aria2c has been restarted.'"]
# startupcmds = ["systemctl --user start aria2d.service"]
# restartcmds = ["systemctl --user restart aria2d.service", "notify-send 'Aria2c has been restarted.'"]

# Used when "Edit Config" option is chosen in the main menu
ariaconfigpath = "~/.config/aria2/aria2.daemon"


# File managers
## Terminal opens in current terminal, and gui_file_manager will fork a new process and open a new application.
terminal_file_manager = "lf"
gui_file_manager = "ghostty -e lf"

# Launchers
## Note that the "open file(s) (grouped)" option still requires gio and xdg-mime.
launch_command = "xdg-open"
# launch_command = "termux-open"


# Time in seconds. If timings are reduced there may be system strain. 1 and 2 seconds are the recommended values.
global_stats_timer = 1
refresh_timer = 2

# Scrolls by default
paginate = false




[appearance]
theme = 4
