#!/usr/bin/env bash

run_once() {
	killall -q -0 "$1" || "$@" &
}

restart_everytime() {
	killall "$1"
	"$@" &
}

source ~/.profile
$HOME/.screenlayout/main.sh
$HOME/.config/polybar/launch.sh
xhost +local:0
xsetroot -cursor_name left_ptr &
run_once xfce4-clipman
run_once picom
restart_everytime dunst
run_once redshift-gtk -l 28.63576:77.22445
run_once lxqt-policykit-agent
run_once unclutter
run_once batterylow
run_once playerctld daemon
# run_once kdeconnect-indicator
run_once autoadb ~/scripts/android-webcam.sh
run_once easyeffects --gapplication-service
# run_once xss-lock -- betterlockscreen --lock --quiet
# run_once sunshine
run_once jellyfin-mpv-shim
# run_once noisetorch
run_once sxhkd

# immersive-wallpapers-x11-cli -f $(ls -t $HOME/.wall.* | head -1) -b "5,0;20,40"
xwallpaper --zoom $(ls -t $HOME/.wall.* | head -1)
nm-applet &
blueman-applet &
# jellyfin-mpv-shim &
# xset dpms 300 300 300

IFS="
"
i=0
for line in $(xrandr --listactivemonitors); do
	if [ $i -eq 0 ]; then
		i=$((i + 1))
		continue
	fi
	IS_PRIMARY=$(
		echo "$line" | grep -F '*' -q
		echo $?
	)
	MONITOR=$(echo "$line" | cut -d' ' -f6)
	if [ $IS_PRIMARY -eq 0 ]; then
		bspc monitor $MONITOR -d 1 2 3 4 5
	else
		bspc monitor $MONITOR -d 6 7 8 9 0
	fi
	i=$((i + 1))
done

bspc config border_width 3
bspc config window_gap 0
bspc config top_padding 0
bspc config bottom_padding 30
bspc config focus_follows_pointer false
bspc config split_ratio 0.7
bspc config borderless_monocle false
bspc config gapless_monocle false

# Colors
bspc config normal_border_color "#555555"
bspc config focused_border_color "#fde047"
bspc config active_border_color "#555555"

# Chat apps
bspc rule -a "Jitsi Meet" desktop='^7' follow=on
bspc rule -a "Element" desktop='^7' follow=on
bspc rule -a "Signal" desktop='^7' follow=on
bspc rule -a discord desktop='^7' follow=on
bspc rule -a "*:telegram-desktop" desktop='^7' follow=on
bspc rule -a *:slack desktop='^7' follow=on

bspc rule -a Gimp desktop='^6' follow=on
bspc rule -a "Transmission-remote-gtk" desktop='^8' follow=on
# bspc rule -a firefox desktop='^2' follow=on
# bspc rule -a Brave-browser desktop='^2' follow=on
bspc rule -a Zathura desktop='^5' follow=on state=fullscreen
bspc rule -a "Com.github.johnfactotum.Foliate" desktop='^5' follow=on state=fullscreen
bspc rule -a "Citra" desktop='^5' follow=on
bspc rule -a "yuzu" desktop='^5' follow=on
bspc rule -a "suyu" desktop='^5' follow=on
bspc rule -a "Cemu" desktop='^5' follow=on
bspc rule -a "Retroarch" desktop='^5' follow=on
bspc rule -a "*:keepassxc" desktop='^8' follow=on
bspc rule -a "*:*:Picture in picture" state=floating
bspc rule -a "*:*:Picture-in-Picture" state=floating
bspc rule -a "*:*:Dialog" state=floating
bspc rule -a "obs" desktop='^9' follow=on
bspc rule -a *:Cmus desktop='^4' follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a scrcpy state=floating
bspc rule -a livecaptions state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
